### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by xMacoy01** [Desamod/CatsGangBot#6]
Activating virtual environment...
Dependencies already installed, skipping installation.
Skipping .env copying
Starting the bot...
Traceback (most recent call last):
  File "C:\Users\x\Desktop\Cats Bot\main.py", line 5, in <module>
    from bot.utils import logger
  File "C:\Users\x\Desktop\Cats Bot\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "C:\Users\x\Desktop\Cats Bot\bot\utils\launcher.py", line 9, in <module>
    from bot.core.tapper import run_tapper
  File "C:\Users\x\Desktop\Cats Bot\bot\core\tapper.py", line 22, in <module>
    from ..utils.tg_manager.TGSession import TGSession
ModuleNotFoundError: No module named 'bot.utils.tg_manager.TGSession'
done
PLEASE EDIT .ENV FILE
Press any key to continue . . .

**Comment by Desamod** [comment]
Use python 3.10

**Comment by Neo19867** [comment]
I am using python 3.11 and have same problem.

**Comment by xMacoy01** [comment]
I am using version 3.11

**Comment by Desamod** [comment]
Please, check README, you need to use only python 3.10 for this bot
