### ISSUE TITLE
ModuleNotFoundError: No module named 'bot.utils.tg_manager.TGSession'

### ISSUE THREAD

**Issue by Ashwin3454** [Desamod/CatsGangBot#7]
(myenv) D:\Bots\cats>python main.py
Traceback (most recent call last):
  File "D:\Bots\cats\main.py", line 5, in <module>
    from bot.utils import logger
  File "D:\Bots\cats\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "D:\Bots\cats\bot\utils\launcher.py", line 9, in <module>
    from bot.core.tapper import run_tapper
  File "D:\Bots\cats\bot\core\tapper.py", line 22, in <module>
    from ..utils.tg_manager.TGSession import TGSession
ModuleNotFoundError: No module named 'bot.utils.tg_manager.TGSession'

(myenv) D:\Bots\cats>

**Comment by Desamod** [comment]
Use python 3.10
